<a href="https://colab.research.google.com/github/yasirylmzcbn/learning-pytorch/blob/main/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
matrix = torch.tensor([[1,2],[9,10]])
matrix

tensor([[ 1,  2],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

### Random Tensors

#### Neural Networks:
1.   Start with random numbers
2.   Look at data
3.   Update random numbers
4.   Step 2


In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5853, 0.8391, 0.9739, 0.6297],
        [0.5170, 0.9382, 0.4358, 0.7678],
        [0.5581, 0.4097, 0.2785, 0.5012]])

In [ ]:
# Create a random tenso rwith similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Zeroes and Ones
zero = torch.zeros(3,4)
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
rn = torch.arange(1, 11)

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = rn)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, )
float_32_tensor

tensor([3., 6., 9.])